### ISSUE TITLE
Do you know any algorithm in Python?

### ISSUE THREAD

**Issue by abranhe** [abranhe/python-lib#23]
<p align="center">
  <img src="https://cdn.abranhe.com/projects/algorithms/algorithms.svg">
</p>

Hi, everyone!

I am creating this library and it would be great if you can help me to include some algorithms in it.

This is a python library for [The All ▲lgorithms project](https://github.com/allalgorithms), which is a huge collection of algorithms implemented in multiple languages.

Happy hacking, and waiting for your contribution.

**Comment by Jonatha-Varjao** [comment]
Hello @abranhe , i can do some help with algorithms related to graphs, like flow, search, and the fancy ones like page-rank.
Just need the guidance along the code-style and the actual algorithms needed to be implemented.

Thanks.
