### ISSUE TITLE
Add an algorithm implementation for 🐍  Python 

### ISSUE THREAD

**Issue by abranhe** [abranhe/python-lib#3]
<p align="center">
  <img src="https://cdn.abranhe.com/projects/algorithms/algorithms.svg">
</p>

Hi, everyone!

I am creating this library and it would be great if you can help me to include some algorithms in it.

This is a python library for [The All ▲lgorithms project](https://github.com/allalgorithms), which is a huge collection of algorithms implemented in multiple languages.

Happy hacking, and waiting for your contribution.

**Comment by rrishabh145** [comment]
What do you want to get done exactly? Please elaborate so that I can help you.

**Comment by abranhe** [comment]
@rrishabh145 This a Python library that will be including a bunch of algorithms, it can be installed:

```
$ pip install allalgorithms
```

This is part of [The All ▲lgorithms](https://github.com/allalgorithms) project. I will be adding a contributing guide, but I haven't had the time.

You can open a pull request here adding a new algorithm but you will need to include along the tests cases and the documentation for it. Otherwise, you can just add a python implementation algorithm with a driven test on it at [github.com/AllAlgorithms/python](https://github.com/allalgorithms/python)

Also, make sure you star our projects 😃!
